{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./flatpak.nix
    ./fonts.nix
    ./home-manager.nix
    ./hyprland.nix
    ./network.nix
    ./nh.nix
    ./nix.nix
    ./nvidia.nix
    ./packages.nix
    ./services.nix
    ./steam.nix
    ./timezone.nix
    ./user.nix
    ./xdg.nix
    ./zram.nix
  ];
}
